// <auto-generated />
using System;
using Investimentos.Fundos.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Investimentos.Fundos.Repository.Migrations
{
    [DbContext(typeof(FundosContext))]
    partial class FundosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Investimentos.Fundos.Domain.Model.Fundo", b =>
                {
                    b.Property<Guid>("IdFundo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CnpjFundo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InvestimentoInicialMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomeFundo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFundo");

                    b.ToTable("Fundo");
                });

            modelBuilder.Entity("Investimentos.Fundos.Domain.Model.Movimento", b =>
                {
                    b.Property<Guid>("IdMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdFundo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoMovimento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorMovimento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMovimento");

                    b.HasIndex("IdFundo");

                    b.ToTable("Movimento");
                });

            modelBuilder.Entity("Investimentos.Fundos.Domain.Model.Movimento", b =>
                {
                    b.HasOne("Investimentos.Fundos.Domain.Model.Fundo", "Fundo")
                        .WithMany("Movimentos")
                        .HasForeignKey("IdFundo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
